### ISSUE TITLE
Visualizar las actividades por mínimo y alícuota

### ISSUE THREAD

**Issue by avdata99** [ModernizacionMuniCBA/ordenanza-tarifaria-anual-ciudad-de-cordoba#1]
Visualización que permita filtros por Ramas y Categoría para ver las actividades comerciales específicas con su alícuota (valor por mil sobre la facturación declarada, campo _alicuota_num_) y su _minimo_ (valor mínimo del pago mensual en caso de que la la alícuota aplicada resulte menor).

Al filtrar las ramas solo se deberían ver las categorías y actividades vinculadas a estas.
Un selector debería poder permitir elegir si queremos visualizar alícuota o mínimo.

La visualización puede ser desde un gráfico de barras verticales con el alto basado en en mínimo o alícuota hasta un gráfico de nodos conectados con el tamaño de los nodos basados en estos mismo números. Puede usar D3, charts de google u otra librería.

**Comment by gastonframirez** [comment]
Probé con el de nodos conectados pero tiene demasiadas actividades y queda todo muy junto. Hice de barras verticales (con navegación por select y por clicks en las barras) y un TreeMap para que los users tengan 2 formas de visualizar.

**Comment by avdata99** [comment]
Me gusta mucho lo que veo. 
Me surgieron alguna dudas y solicitudes de cambios.
Cuando elegís rama pero no categoría ¿Se muestra el total de cada categoría?
Si es así, pasalo al promedio y que se vea que es promedio (pone la palabra _promedio_ antes del total del mínimo o alícuota). 
El mínimo arriba en el filtro debería llamarse _mínimo mensual_ para que se entienda mejor.
En el caso de las alícuotas, son $. Ponele el simbolo cada vez que se llame a esa cifra. A ese numero sacale por favor las abreviaturas con k (con 1.25K para decir $1.250). El separador de mil puede quedar pero no la K.
Las alícuotas son por mill (como el % pero dividido 10). Mostra esos números con el símbolo % y diviilos por 10 para que se entienda más

**Comment by gastonframirez** [comment]
Agrandar los tooltips

**Comment by Facundobarrionuevo** [comment]
Sacar la palabra promedio de cada valor. Poner promedio en el título del eje:

![image](https://user-images.githubusercontent.com/20156968/28270390-b29c6df0-6adb-11e7-8a2c-448c536dcac5.png)

Achicar espacio:

![image](https://user-images.githubusercontent.com/20156968/28270402-b97dae68-6adb-11e7-8a68-d0ede2e5fbdb.png)

**Comment by gastonframirez** [comment]
@Facundobarrionuevo ahi cambié lo de "Promedio". El tamaño del overlay es medio complicado, porque en la parte de las actividades, como el titulo de algunas es muy largo queda mal. Por eso está asi de ancho. Tenemos 2 opciones:
- Lo dejamos asi de ancho para todo.
- Lo ponemos un poco mas chico para Ramas y Categorias, y asi de grande para Actividades.

Avisame!

**Comment by Facundobarrionuevo** [comment]
Lo ponemos un poco mas chico para Ramas y Categorias, y asi de grande para Actividades.
