### ISSUE TITLE
Crear Visualización 2018

### ISSUE THREAD

**Issue by avdata99** [ModernizacionMuniCBA/ordenanza-tarifaria-anual-ciudad-de-cordoba#4]
Ya tenemos los datos de la Ordenza Tarifaria Anual 2018

La [visualizacion 2017](https://modernizacionmunicba.github.io/ordenanza-tarifaria-anual-ciudad-de-cordoba/#b-a-0-0) funciona perfecto y es la que hay que replicar.

![image](https://user-images.githubusercontent.com/3237309/42282100-d7034b5e-7f7b-11e8-8b2a-fa3f5f831793.png)

En primer lugar en el header hay que poner un selector de año (solo opciones 2017 y 2018).
La opción 2017 no debería cambiar de fuente de datos ni nada. La viz 2018 es el motivo de este ticket y  debe ir a la nueva fuente de datos.
Esta nueva fuente es un CSV que se construye automáticamente desde el sistema Qhapax. [Este es el link](http://gobiernoabierto.cordoba.gob.ar/tarifaria/lista-de-rubros-2018.csv). La visualizacion 2018 debe consumir los datos desde allí.

Conservar la variabilidad de la URL. Al cambiar de rama o categorías de actividad la URL debe cambiar. Esto tiene que seguir funcionando

**Comment by avdata99** [comment]
Si es necesario separa el código en dos no hay problema.
Evitemos complicaciones para usar dos fuentes de datos distintas con el mismo código.
Si fuera muy facil, usemos el mismo código, sino dupliquemos, no es problema

**Comment by maxieric** [comment]
@avdata99 con respecto a esto? Hace falta alguna modificación?

**Comment by avdata99** [comment]
Hubo un tema con las ramas. Github inicialmente solo permitía _publicar como web_ una rama que debía llamarse gh-pages. Como este repo es viejo esa es la rama de la que deberías haber salido con tu nueva rama. No es grabe, adapté yo el código y quedo andando. Te paso los detalles como nuevos tickets
