### ISSUE TITLE
Predeterminar 2018

### ISSUE THREAD

**Issue by avdata99** [ModernizacionMuniCBA/ordenanza-tarifaria-anual-ciudad-de-cordoba#5]
Hacer que la home de este sitio sea el año 2018.
Pensar en que los links sean permanentes y no tengan que cambiar cada año.
Posiblemente index.html deba renombrarse a 2017.html y crear en index una home con la lista de los años disponibles (sin quitar el menu del header)

Hacer tambien que el menu de los años del header tenga algún icono o algo que deje claro que es un menu desplegable (posiblemente un triangulito apuntando hacia abajo o similar) y no un simple indicador del año.

Hacer una rama nueva a partir de la rama _gh-pages_ (actualizando antes los cambios)
Al terminar hacer un PR (presionando el boton _new pull request_ parado en la nueva rama en github.com) asignado a mi al terminar. Preguntar a Maycol si es que no sale

**Comment by maxieric** [comment]
@avdata99 crear en index una home con la lista de los años disponibles (sin quitar el menu del header), esta parte no entendi bien, como una home? Cree un home.html para poder elegir el año, pero no se si es exactamente lo que me solicitas.

**Comment by avdata99** [comment]
Si, sería como una home pero solo con los dos links a 2017.html y 2018.html
Además el menu de seleccion de años en el header queda. En realidad no cambia nada más
La home quizas quede un poco escueta. Si se te ocurre algo como un logo de la muni o gobierno abierto, ponelo

**Comment by avdata99** [comment]
Ahora que lo pienso en la home podes poner un texto explicativo

```
La Ordenanza Tarifaria Anual (OTA) de la Ciudad de Córdoba es una norma que todos los años el Concejo Deliberante sanciona como Ordenanza.

Todas estas ordenanzas además de en el digesto municipal quedan (registradas en nuestro portal de datos abiertos)* 

* link a https://gobiernoabierto.cordoba.gob.ar/data/datos-abiertos/categoria/marco-legal/ordenanza-tarifaria-anual/189

Entre otros detalles, dentro de la OTA se incluye la lista de alícuotas y mínimos mensuales por el ejercicio de la actividad comercial, industrial o de servicios.

Esta lista tienen todos los códigos de actividad comercial (que tambien [están publicados]* que son los que se toman como base en estas visualizaciones.

* link a https://gobiernoabierto.cordoba.gob.ar/data/datos-abiertos/categoria/ingreso/detalle-de-la-ordenanza-tarifaria-anual/200

Visualizaciones disponibles:
Ramas, Categorías y Actividades comerciales de la OTA 2017 con sus alícuotas y mínimos: 2017.html
Ramas, Categorías y Actividades comerciales de la OTA 2017 con sus alícuotas y mínimos: 2018.html
```
